server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 222222
    url: jdbc:mysql://localhost:3306/db_dstorage
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl